/*
 * Ported to Java from OpenMW (https://openmw.org)
 * Original work Copyright (C) OpenMW Contributors
 * Java translation Copyright (C) 2026 JVM-MW contributors
 */
package io.github.jvmmw.esm;

import java.util.ArrayList;
import java.util.List;

/**
 * A cell’s NPC walk graph from the ESM: points and the edges between them.
 * Wander still goes in a straight line; this is the dump so we can follow
 * the graph later. Points are cell-local TES (exteriors 0–8192 in that
 * cell). Wander adds the cell origin and follows the edges.
 */
public final class EsmPathgrid {
    public static final EsmPathgrid NONE = new EsmPathgrid();

    public String name = "";
    public int gridX;
    public int gridY;
    public int granularity;
    public final List<Point> points = new ArrayList<>();
    public final List<Edge> edges = new ArrayList<>();

    public static final class Point {
        public int x;
        public int y;
        public int z;
        public int autogenerated;
        public int connections;
    }

    public static final class Edge {
        public int v0;
        public int v1;
    }
}
